version: '3.1'

networks:
  production-network:
    driver:
      bridge

services:
  backend-service:
    image: backend-bb
    container_name: backend-bb
    hostname: backend-bb
    restart: always
      
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
      
    ports:
      - "8080:8080"
    networks:
      - production-network

  frontend-service:
    image: frontend-bb
    container_name: frontend-bb
    hostname: frontend-bb
    restart: always
      
    build:
      context: ./frontend
      dockerfile: Dockerfile
      
    ports:
      - "4200:80"
    networks:
      - production-network
